Repository OnlyUseMeRocket/auto-catan, pull requests merged in 2024-11, with the labels that each got.

#2 chore: add README
  README.md
  iac/1-install-k3s.sh
  iac/1-install-kubectl.sh
  iac/2-install-k3s.sh
Labels: enhancement

#7 feat(iac): implemented helm installation script
  .kubectl_aliases
  iac/1-install-kubectl.sh
  iac/3-install-helm.sh
Labels: enhancement

#8 chore(docs): add troubleshooting issues related to dealing with coredns
  README.md
Labels: documentation

#13 fix(iac): changed kubeconfig to be defined in user home directory
  README.md
  iac/2-install-k3s.sh
Labels: bug

#14 feat(merge): finish minio dependency feature implementation
  .gitignore
  Tiltfile
  deploy/.helmignore
  deploy/Chart.lock
  deploy/Chart.yaml
  deploy/values.yaml
Labels: enhancement
